import type { Metadata } from "next";
import "./globals.css";

import { Oswald } from "next/font/google";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";

const font = Oswald({
	variable: "--font-oswald",
	display: "swap",
	subsets: ["latin"],
	weight: "variable",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={`${font.className}} antialiased`} lang="en">
      <body className="bg-swGrey">

        <div className="page-wrapper h-screen">
          <Header />

            <h2 className=" text-white text-4xl text-center pt-5 pb-10">
              Welcome to Dave&apos;s Star Wars DB. Filter your results by clicking a button below
            </h2>

            {children}

          <Footer/>
        </div>
      </body>
    </html>
  );
}
